nephila/django-meta

- README.rst
The Readme has the wrong attributes for the Meta class, so I fixed them.
According to https://github.com/nephila/django-meta/blob/develop/meta/views.py#L19-20 there is no ``meta_extras`` or ``custom_meta_extras`` attributes on Meta
I switched ``meta_extras`` with ``extra_props`` and ``custom_meta_extras`` with ``extra_custom_props``
> updated incorrect information in readme file.

- meta/templatetags/meta.py
- tests/test_templatetags.py
I have realized the current template tags are not escaping special characters, which might result in XSS problems. I introduced escaping to `custom_meta` base method and refactored the code to reuse it. @murataydos @yakky can you review? Thanks.
> Escape values before rendering them in template.

- meta/views.py
- tests/test_meta.py
> Support schema-less URLs (eg //foo.com/foo/bar )

- README.rst
- docs/installation.rst
As per [their blog post of the 27th April](https://blog.readthedocs.com/securing-subdomains/) ‘Securing subdomains’:
> Starting today, Read the Docs will start hosting projects from subdomains on the domain readthedocs.io, instead of on readthedocs.org. This change addresses some security concerns around site cookies while hosting user generated data on the same domain as our dashboard.
Test Plan: Manually visited all the links I’ve modified.
> Convert readthedocs links for their .org -> .io migration for hosted projects

- HISTORY.rst
- meta/templates/meta/meta.html
to suppress redundant newlines
Fix #51
> Wrap meta.html content in spaceless templatetag

- meta/views.py
I suppose it's a bug. It escalated when I didn't call 'super' in my class using MetadataMixin ->
AttributeError: 'MyClass' object has no attribute 'use_title_tag'
> Fix MetadataMixin.use_use_title_tag -> MetadataMixin.use_title_tag

- HISTORY.rst
- docs/settings.rst
- meta/settings.py
- meta/templatetags/meta.py
- tests/test_mixin.py
- tests/test_templatetags.py
By wrapping the logic inside the templatetag we can avoid any template change and 
make this change fully compatible with customized templates
Fix #79
> Add support for og:image:secure_url

- AUTHORS.rst
- HISTORY.rst
- meta/models.py
- tests/example_app/models.py
- tests/test_mixin.py
Alternative approach to #85 
We rely on `AttributeError` exception instead of `hasattr` for efficiency and cleanliness
Fix #85 
Fix #86
> Alternative fix for #85

- docs/views.rst
- meta/models.py
- meta/templates/meta/meta.html
- meta/views.py
- tests/example_app/models.py
- tests/test_mixin.py
According to Facebook documentation
https://developers.facebook.com/docs/sharing/best-practices/?locale=en_US#precaching
adding   og:image:width and og:image:height properties will help facebook crawler to figure out right image dimensions. It will render the shared image at the first post sharing.
Currently, the first person who shares the post doesn't see the image. The image becomes available after the second post.
> Add image size for facebook sharing

- cms_helper.py
This is mostly useful when integrating external testing tools (e.g.: PyCharm integrated debugger)
> Init djangocms-helper when loading cms_helper as module

- meta/templatetags/meta.py
- setup.py
- tox.ini
Fixes issue #96 regarding the use of deprecated internal Django APIs causing incompatibility with Django 3.0.
~~Seeing as Python 2 EOL is getting dangerously close I also dropped anything related to Python 2.~~ (see below comment)
> Add Django 3.0 support

- .travis.yml
- HISTORY.rst
- requirements-test.txt
- setup.py
As we removed django shims in #97 
See https://github.com/nephila/django-meta/commit/5d8238b8b93d395cacd6a3febb072a844898f9cb#commitcomment-36818229
Thanks @2tunnels  for reporting
> Add explicit six dependency

- meta/models.py
There is a small typo in meta/models.py.
Should read `request` rather than `requst`.
> docs: Fix simple typo, requst -> request

- meta/templatetags/meta.py
- tests/test_mixin.py
- tests/test_templatetags.py
Render both `og:image` and `og:image:secure_url` if https is enabled
Fix #79 
Fix #107
> Fix support for secure_url

- README.rst
- docs/views.rst
- meta/models.py
- meta/templates/meta/meta.html
- meta/templatetags/meta.py
- meta/views.py
- tests/example_app/models.py
- tests/example_app/urls.py
- tests/example_app/views.py
- tests/test_meta.py
- tests/test_metadata_mixin.py
- tests/test_mixin.py
- tests/test_templatetags.py
Add support for ``image_object`` property, to allow managing all the og:image properties (url, alt, height, width) with a single property
Original ``image`` property is kept for compatibility purposes, but if ``image_object`` is set, its value it's ignored and the ``image_object`` url is used instead
> Add support for image object

- changes/115.bugfix
- cms_helper.py
- meta/models.py
- meta/utils.py
- requirements-test.txt
- tests/example_app/models.py
- tests/test_asgi.py
- tests/test_mixin.py
- tox.ini
Use thread locals to store request to build absolute url
This is safer in general, and especially in ASGI environment. If ASGI (which ships its own version) is not available, we use threading local
Move to pytest runner to run async tests (though not on ASGI)
Fix #115
> Switch request handling to thread locals

- .github/workflows/lint.yml
- .github/workflows/publish.yml
- .github/workflows/test.yml
- .pre-commit-config.yaml
- changes/135.bugfix
- cms_helper.py
- setup.cfg
- tasks.py
- tox.ini
- Update supported Python and Django versions in tox, github actions and setup.cfg
- Update github actions versions
- Fix missing SECRET_KEY in django-app-helpers settings
Fix #135
> Update supported Python and Django versions

- changes/133.bugfix
- meta/models.py
- tests/test_meta.py
- tests/test_metadata_mixin.py
- tests/test_mixin.py
Use the correct setting name (`USE_SITES` instead of `META_USE_SITES`) from the correct setting module (`meta.settings` instead of `django.conf.settings`)
Fix #133 
Fix #134
> Merge #134

- CONTRIBUTING.rst
- docs/installation.rst
- docs/models.rst
- docs/views.rst
There are small typos in:
- CONTRIBUTING.rst
- docs/installation.rst
- docs/models.rst
- docs/views.rst
Fixes:
- Should read `passing` rather than `passsing`.
- Should read `overridden` rather than `overidden`.
- Should read `instead` rather than `insteaf`.
- Should read `development` rather than `developement`.
- Should read `containing` rather than `containig`.
- Should read `compliance` rather than `compliancy`.
Semi-automated pull request generated by
https://github.com/timgates42/meticulous/blob/master/docs/NOTE.md
> docs: Fix a few typos

- changes/155.bugfix
- meta/views.py
- tests/test_meta.py
Move setting Meta.request at the start of __init__ method, to be able to use request object when setting other attributes
Fix #155
> Fix request set order in Meta.__init__

- changes/127.bugfix
- meta/views.py
- tests/example_app/migrations/0001_initial.py
- tests/example_app/models.py
- tests/test_meta.py
- tests/test_metadata_mixin.py
- tests/test_mixin.py
Fix schemaorg_description not being in Meta class
Fix #127
> Fix schemaorg_description not being in Meta class

- changes/167.feature
- cms_helper.py
- meta/models.py
- meta/settings.py
- meta/templatetags/meta.py
- meta/views.py
- tests/test_asgi.py
- tests/test_meta.py
- tests/test_metadata_mixin.py
- tests/test_mixin.py
Refactor settings to make override_settings in tests more consistent
Fix #167
> Refactor settings to make override_settings in tests more consistent

- changes/182.feature
- meta/models.py
- meta/views.py
I have removed unnecessary "else" statements.
Fix #182
> Removed unnecessary "else" statements.

- changes/192.bugfix
- meta/views.py
- tests/test_meta.py
Refactor FullUrlMixin get_domain to handle django.contrib.sites not in INSTALLED_APPS
Fix #192
> Refactor FullUrlMixin get_domain to handle django.contrib.sites not in INSTALLED_APPS

- .github/workflows/test.yml
- README.rst
- changes/216.feature
- setup.cfg
- tox.ini
Add support for Django 5.2 and python 3.12 and 3.13. Original pr was #215 , thanks to @kirmola .
Fix #216
> Add support for Django 5.2 and python 3.12 and 3.13, drop support for Django 3.2
