README.rst, meta/templates/meta.html, meta/views.py, tests/test_meta.py, tests/test_metadata_mixin.py
Hi guys,
I added some missing properties on the twitter namespace: `creator` and `card`. (documentation here https://dev.twitter.com/cards/getting-started). Added documentation and tests.
Let me know if this works for you,
Max.
=> More twitter properties

meta/views.py, tests/test_metadata_mixin.py
Hi,
I updated the MetadataMixin by adding a way to configure the meta object name in the context. I also moved the meta object initialization to a dedicated method in order to ease customization.
=> Improved customization

CHANGELOG.rst, meta/templates/meta.html
Fix #15 
Thanks @tarlabs for suggestion
=> Use autoescape off in template for Django 1.9

tests/example_app/models.py, tests/example_app/urls.py, tests/example_app/views.py, tests/test_metadata_mixin.py, tests/test_mixin.py
=> Add test for issue #11

README.rst, docs/index.rst, docs/installation.rst
=> Fix installation docs

.travis.yml, HISTORY.rst, cms_helper.py, docs/installation.rst, docs/rendering.rst, meta/templates/meta/meta.html, meta/templatetags/meta.py, meta/views.py, setup.py, tests/example_app/south_migrations/0001_initial.py, tests/example_app/south_migrations/__init__.py, tests/example_app/templates/example_app/post_detail.html, tests/example_app/templates/example_app/post_list.html, tests/example_app/urls.py, tox.ini
By using some tricks we can make sekizai not required anymore in a backward compatible way
=> Remove sekizai dependency

docs/settings.rst, meta/views.py, tests/test_meta.py
=> Properly implement META_DEFAULT_IMAGE for view-based mixins

meta/models.py, tests/test_mixin.py
=> Removed dependency of sites framework

meta/templates/meta/meta.html, meta/templatetags/meta.py, tests/test_templatetags.py
=> Fix facebook_prop templatetag

docs/settings.rst, docs/views.rst
Putting the Meta object first it should clarify how to use it
Fix #37
=> Propose documentation fix

README.rst
=> Rephrase Django / Python versions support

meta/templates/meta/meta.html, tests/test_mixin.py
Hi @yakky 
This fixes some OG properties for twitter. Also, it might be nice to have tests on the template itself :)
Twitter reference: https://dev.twitter.com/cards/markup
=> fix twitter props

HISTORY.rst, meta/views.py, tests/test_meta.py
=> Fix error with META_DEFAULT_IMAGE path

README.rst, docs/index.rst
=> Add contributed apps section to readme

docs/views.rst, meta/models.py, meta/views.py, tests/test_meta.py, tests/test_mixin.py
=> Add optional request argument to Meta

docs/views.rst, meta/__init__.py, meta/models.py
Fix a little mistake on documentation
=> Fix Meta object example in documentation

.travis.yml, HISTORY.rst, docs/conf.py, docs/extra_tags.rst, docs/index.rst, docs/models.rst, docs/views.rst, meta/models.py, setup.py, tests/example_app/models.py, tests/example_app/views.py, tests/test_mixin.py, tox.ini
- Improve documentation
- Improve examples
- Fix an error preventing usage for scalar values
Fix #92 
Fix #82
Fix #63
=> Improve support for extra / custom props

cms_helper.py, requirements-test.txt, tests/test_mixin.py, tox.ini
Enable adding support for django 3.0+
=> Move djangocms-helper to django-app-helper

meta/templatetags/meta.py, tests/test_mixin.py, tests/test_templatetags.py
Fix support for secure_url on 1.6 branch
=> Fix support for secure_url

docs/views.rst, meta/views.py, tests/test_meta.py, tests/test_metadata_mixin.py
=> Normalize twitter_card / twitter_type attributes

.github/workflows/test.yml, README.rst, changes/144.feature, meta/models.py, meta/templatetags/meta.py, meta/views.py, setup.cfg, tests/example_app/urls.py, tox.ini
Add Django 4.2 / Python 3.11 to test matrix
Drop Python < 3.9, Django <3.2
Fix #144
=> Add support for Django 4.2

.bumpversion.cfg, .github/workflows/lint.yml, .github/workflows/test.yml, .gitignore, .pre-commit-config.yaml, changes/138.feature, pyproject.toml, setup.cfg, tasks.py, tests/example_app/urls.py, tox.ini
=> Move to ruff

README.rst
Describe:
* Content of the pull request
* Feature added / Problem fixed
Provide any github issue fixed (as in ``Fix #XYZ``)
=> update documentation 

changes/152.bugfix, meta/templatetags/meta.py, tests/test_mixin.py, tests/test_templatetags.py
Fix schema.org procol:
- original commit taken from #152 by @svandeneertwegh
- fix tests and ci 
Original pr: #152
=> Fix schema org protocol

meta/views.py
ValueError message was "intrable". I have changed it to "iterable".
Provide any github issue fixed (as in ``Fix #XYZ``)
=> Changed/Fixed error message.

.github/workflows/test.yml, changes/188.feature
Switch to Coveralls Github action
Fix #188
=> Switch to Coveralls Github action

changes/213.bugfix, docs/conf.py
=> Fix docs build

.github/workflows/test.yml, changes/222.bugfix
Bump Github actions/cache tag version
Fix #222
=> Bump Github actions/cache tag version
